name: Node CI

on:
  push:
    paths:
    - 'packages/zaml-editor/**'

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Build Editor
      run: |
        yarn install
        yarn run build
      working-directory: packages/zaml-editor
      env:
        CI: true
    - name: Deploy Editor
      run: |
        yarn run deploy
      working-directory: packages/zaml-editor
      env:
        CI: true
